apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 3-apps/plex
    repoURL: https://github.com/benswinney/microshift-homelab.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true